import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import {Inter, Montserrat} from "next/font/google";
import "./globals.css";
import React, {Suspense} from "react";
import { BrowserRouter } from 'react-router-dom'
import {Providers} from "@/lib/providers";
import {ThemeProvider} from "next-themes";
import Header from "@/components/header/header";
import {FullPageSection} from "@/components/common/fullPageSection";
import {Loader} from "lucide-react";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const inter = Inter({ subsets: ["latin"] });

const montserrat = Montserrat({subsets: ["latin"]});
export const metadata = {
  title: "FinanceManager",
  description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{children: React.ReactNode; }>) {
  return (
      <Providers>
          <html lang="en" suppressHydrationWarning>
          <body className={montserrat.className}>
          <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
          >
              <Header/>
              <Suspense fallback={<FullPageSection
                  className={"flex justify-center items-center"}><Loader/></FullPageSection>}>
                  {children}
              </Suspense>
          </ThemeProvider>
          </body>
          </html>
      </Providers>
  );
}
