import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Inter } from "next/font/google";
import "./globals.css";
import React from "react";
import { BrowserRouter } from 'react-router-dom'
import {Providers} from "@/lib/providers";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "LucyusBeats",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{children: React.ReactNode; }>) {
  return (
      <Providers>
        <html lang="en">
        <body className={inter.className}>{children}</body>
        </html>
      </Providers>
  );
}
